### ISSUE TITLE
您好，我想尝试运行下您的代码，但下载稀疏矩阵和输入正弦图的网址无法正常打开，能分享一下吗

### ISSUE THREAD

**Issue by FANTYMAN** [wangwei-cmd/CT-image-reconstruction#2]
如果可以的话，希望您能将文件以附件的形式发送到我的邮箱

**Comment by wangwei-cmd** [comment]
你好，我已经把链接换成百度云了。

**Comment by FANTYMAN** [comment]
好的，非常感谢！

**Comment by FANTYMAN** [comment]
老师，您好，请问训练完比较网络后，如何对模型进行测试。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月29日 00:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wangwei-cmd/CT-image-reconstruction] 您好，我想尝试运行下您的代码，但下载稀疏矩阵和输入正弦图的网址无法正常打开，能分享一下吗 (Issue #2) |

你好，我已经把链接换成百度云了。
